name: npm-automation-latest

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  npm-automation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        index: [1,2] # 10 jobs per OS → 3 OS * 10 = 30
      max-parallel: 12
    env:
      UNIQUE_ID: ${{ github.run_id }}-${{ matrix.os }}-${{ matrix.index }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean NPM Cache
        run: npm cache clean --force

      - name: Install Latest Package
        run: npm install dependency-insight@latest

      - name: Run Script
        run: node -e "require('./node_modules/dependency-insight'); console.log('Running from $UNIQUE_ID');"

      - name: Clean Environment (cross-platform)
        run: |
          node -e "const fs = require('fs'); ['node_modules','package-lock.json'].forEach(f=>{fs.existsSync(f)&&fs.rmSync(f,{force:true,recursive:true})});"
